# Base
brew "git"
brew "gnupg"
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "jq"
brew "yq"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "bat"
brew "eza"
brew "tmux"
brew "neovim"
brew "stow"

# Zsh extras
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "starship"

# Web / bug bounty (herramientas de sistema)
brew "nmap"
brew "masscan"
brew "ffuf"
brew "gobuster"
brew "wget"
brew "curl"
brew "openssl@3"

# Go (necesario para instalar herramientas de ProjectDiscovery y tomnomnom)
brew "go"

# ProjectDiscovery y tomnomnom
# El tap oficial falla con autenticacion HTTPS en algunos entornos.
# Instalar con go install despues de brew bundle:
#
#   go install github.com/projectdiscovery/httpx/cmd/httpx@latest
#   go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
#   go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
#   go install github.com/projectdiscovery/katana/cmd/katana@latest
#   go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest
#   go install github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
#   go install github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest
#   go install github.com/tomnomnom/anew@latest
#   go install github.com/tomnomnom/unfurl@latest
#   go install github.com/tomnomnom/assetfinder@latest
#   go install github.com/d3mondev/puredns/v2@latest
#
# O usar el script: scripts/.local/bin/install-go-tools

# Containers (alternativa a Docker Desktop)
brew "colima"
brew "docker"
brew "docker-compose"

# Python tooling
brew "pipx"
brew "python@3.12"

# Opcional (descomenta si lo usas)
# brew "wireshark"
# brew "--cask burp-suite-community"
