# Base
brew "git"
brew "gnupg"
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "jq"
brew "yq"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "bat"
brew "eza"
brew "tmux"
brew "neovim"

# Zsh extras
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "starship"

# Web / bug bounty
brew "nmap"
brew "masscan"
brew "ffuf"
brew "nuclei"
brew "gobuster"
brew "wget"
brew "curl"
brew "openssl@3"

# Containers (alternativa a Docker Desktop)
brew "colima"
brew "docker"
brew "docker-compose"

# Python tooling
brew "pipx"

# Opcional (descomenta si lo usas)
# brew "wireshark"
