# Desactiva sonidos molestos
enable_audio_bell no

# Carga tus colores pastel bonitos
include color.ini

# Fuente aesthetic
font_family "Hack Nerd Font"
font_size 13

# Ligaduras (como en Fira Code) habilitadas
disable_ligatures never

# Enlaces detectables y en azul suave
url_color #a3ecf8
url_style curly

# Navegación entre ventanas con Ctrl+Flechas
map ctrl+left  neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up    neighboring_window up
map ctrl+down  neighboring_window down

# Copiar/pegar en buffers con F1–F4
map f1 copy_to_buffer a
map f2 paste_from_buffer a
map f3 copy_to_buffer b
map f4 paste_from_buffer b

# Cursor rosa subrayado y fino
cursor_shape underline
cursor_underline_thickness 2.0

# Oculta el ratón tras 3s sin moverse
mouse_hide_wait 3.0
detect_urls yes

# Optimización de render
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Estética de pestañas cuqui
tab_bar_style powerline
inactive_tab_background #f28fdd
active_tab_background   #ffb3d6
inactive_tab_foreground #000000
tab_bar_margin_color    #1a1b26

# Crear ventana o pestaña nueva con atajos
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t     new_tab_with_cwd

# Fondo ligeramente translúcido (si tienes picom)
background_opacity 0.92

# Shell por defecto: zsh con tus dotfiles
shell zsh
