cursor_shape              Underline
cursor_underline_thickness 1
window_padding_width      20

# Especiales
# Rosa pastel claro
foreground                #ffccdd
# Negro profundo con matiz violeta
background                #1a1b26

# Black
color0                    #414868
color8                    #414868

# Red (rosado fuerte)
color1                    #f7768e
color9                    #f7768e

# Green (menta)
color2                    #73daca
color10                   #73daca

# Yellow (vainilla)
color3                    #e0af68
color11                   #e0af68

# Blue (azul lavanda)
color4                    #7aa2f7
color12                   #7aa2f7

# Magenta (pastel + rosita)
color5                    #bb9af7
color13                   #ffacee

# Cyan (turquesa pastel)
color6                    #7dcfff
color14                   #a3ecf8

# White (rosa blanquecino)
color7                    #ffd9e6
color15                   #ffe9f0

# Cursor
cursor                    #ffb3d6
cursor_text_color         #1a1b26

# Selection
selection_foreground      #1a1a1a
selection_background      #ffd9e6
