[color]

; Fondos
bg       = #1a1b26
bg-alt   = #262736
white    = #fefefe
gray     = #7f849c
black    = #1a1a1a

; Acents
pink     = #ffb3d6
magenta  = #ff79c6
blue     = #8be9fd
green    = #50fa7b
yellow   = #f1fa8c
red      = #ff5555

; Texto
fg       = #ffd9e6
fg-alt   = #ffccdd
