; ─────── TheOffSecGirl Polybar Pastel 💖 ───────

[global/wm]
margin-top = 0
margin-bottom = 0

include-file = ~/.config/polybar/colors_pastel.ini

[bar/main]
monitor = HDMI-1
bottom = false
fixed-center = true

width = 100%
height = 36
offset-x = 0
offset-y = 0

background = ${color.bg}
foreground = ${color.fg}

radius-top = 10.0
radius-bottom = 10.0

line-size = 2
line-color = ${color.magenta}
border-bottom-size = 0
border-color = ${color.magenta}

padding = 2
module-margin-left = 4
module-margin-right = 4

font-0 = "Iosevka Nerd Font:size=12;3"
font-1 = "Iosevka Nerd Font:bold:size=18;3"
font-3 = "JoyPixels:size=1;0"
font-2 = "Hack Nerd Font:size=15;4"

modules-left = my-text-label net_status motibar
modules-center = bspwm workspaces spotify
modules-right = target sep2 vpn sysmenu 

wm-restack = bspwm
enable-ipc = true

;; ───────────── MODULES ─────────────

[module/my-text-label]
type = custom/text
content = %{T3}
content-foreground = ${color.magenta}
content-padding = 1

[module/net_status]
type = custom/script
exec = ~/.config/bspwm/scripts/net_status.sh
interval = 5
format-foreground = ${color.fg}

[module/vpn]
type = custom/script
exec = ~/.config/bspwm/scripts/vpn_status.sh
interval = 5
format-foreground = ${color.fg}
click-left = ~/.config/bspwm/scripts/vpn_open.sh

[module/target]
type = custom/script
exec = ~/.config/bspwm/scripts/target.sh
interval = 2
format-foreground = ${color.pink}

[module/sep2]
type = custom/text
content = "  |  "
content-foreground = ${color.gray}

[module/sysmenu]
type = custom/text
content = %{T3}⏻
content-foreground = ${color.fg}
click-left = ~/.config/polybar/scripts/powermenu_alt

[module/date]
type = internal/date
interval = 5
date = %d %b
time = %H:%M
label = %{T2}  %date% | %{T2}  %time%
format-foreground = ${color.fg}
label-font = 2

[module/motibar]
type = custom/script
exec = ~/.config/bspwm/scripts/motivacion.sh
interval = 10
click-left = ~/.config/bspwm/scripts/motivacion.sh --force && polybar-msg hook motibar 1
format-foreground = ${color.pink}

[module/spotify]
type = custom/script
exec = ~/.config/bspwm/scripts/spotify.sh
interval = 2
format-foreground = ${color.fg}

click-left = playerctl previous
click-right = playerctl next
click-middle = playerctl play-pause

scroll-up = pamixer -i 5
scroll-down = pamixer -d 5

[module/workspaces]
type = internal/bspwm
format = <label-state>
pin-workspaces = true

label-focused = %{T2}
label-focused-foreground = #1a1a1a
label-focused-background = #ffb3d6
label-focused-padding = 2
label-focused-font = 2

label-occupied = %{T2}󰋑
label-occupied-foreground = #ffb3d6
label-occupied-padding = 2
label-occupied-font = 2

label-empty = %{T2}󰴔
label-empty-foreground = #ffd9e6
label-empty-padding = 2
label-empty-font = 2
